version: '3.9' # optional since v1.27.0
services:
  mysql-ts-shop:
    image: mysql
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=ts-shop-db
      - MYSQL_ROOT_PASSWORD=quang123
    ports:
      - '3306:3306'
    volumes:
      - db:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
  db:
    driver: local
