import type { NextPage } from 'next'
import * as React from 'react'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

const Home: NextPage  = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />

        <script src="https://accounts.google.com/gsi/client" async defer></script>
        <div id="g_id_onload"
          data-client_id="878722088107-g3a1a44g52ushfvm134i5976dhn9gb54.apps.googleusercontent.com"
          data-ux_mode="redirect"
          data-login_uri="http://localhost:8008/auth/google/callback">
        </div>
        <div className="g_id_signin" data-type="standard"></div>
      </Head>

      <main className={styles.main}>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
