// export enum STREAMING {
//   CONNECT_TO_STREAM = 'SOCKET:STREAMMING:CONNECT_TO_STREAM',
// }

const socketType = 'SOCKET:STREAMING'

export const STREAMING = {
  CONNECT_TO_STREAM: `${socketType}:CONNECT_TO_STREAM`,
  WATCHER__SUBSCRIBE: `${socketType}:WATCHER_SUBSCRIBE`,
  WATCHER_SEND_DESCRIPTION: `${socketType}:WATCHER_SEND_DESCRIPTION`,
  STREAMER_INITIATE: `${socketType}:STREAMER_INITIATE`,
  STREAMER_SEND_DESCRIPTION: `${socketType}:STREAMER_SEND_DESCRIPTION`,
  ADD_CANDIDATE: `${socketType}:ADD_CANDIDATE`,
}

